SynchroTime: Console Class Reference
Console Class Reference
The Console class.
#include <console.h>
Signals
void getData (const QByteArray &data)
Public Member Functions
Console (QWidget *parent=0)
Console::Console.
~Console ()
Console::~Console.
void putData (const QString &data)
Console::putData.
void setLocalEchoEnabled (bool set)
Console::setLocalEchoEnabled.
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *e)
Console::keyPressEvent.
virtual void mousePressEvent (QMouseEvent *e)
Console::mousePressEvent.
virtual void mouseDoubleClickEvent (QMouseEvent *e)
Console::mouseDoubleClickEvent.
virtual void contextMenuEvent (QContextMenuEvent *e)
Console::contextMenuEvent.
Private Member Functions
const QString formatHtml (const QString &qText, const QColor &qColor=QColor(Qt::green)) const
Console::formatHtml.
Private Attributes
bool localEchoEnabled
QByteArray * buffer
Detailed Description
The Console class.
Provides the user with methods for the console interface.
Constructor & Destructor Documentation
Console::Console (QWidget * parent = 0) explicit
Console::Console.
Standard constructor
Parameters
parent of the type *QWidget - main application window (*MainWindow)
References buffer.
Console::~Console ()
Console::~Console.
Default destructor
References buffer.
Member Function Documentation
void Console::contextMenuEvent (QContextMenuEvent * e) protected virtual
Console::contextMenuEvent.
Parameters
e
const QString Console::formatHtml (const QString & qText, const QColor & qColor = QColor(Qt::green)) const private
Console::formatHtml.
This helper function solves the formatting problem. The problem is that plain text can contain special characters that have meta-values in HTML, literally: <> & "'. This is solved by a simple formatter that converts them to their corresponding HTML entities. For example, the function converts the end of the line "\ n" to "<br/>".
Parameters
qText of the type const QString. Block of text to convert to HTML.
qColor of the type const QColor. The color for the block of text.
Returns
qHtmlText of the type const QString.
Referenced by putData().
void Console::getData (const QByteArray & data) signal
Referenced by keyPressEvent().
void Console::keyPressEvent (QKeyEvent * e) protected virtual
Console::keyPressEvent.
Parameters
e
References buffer, getData(), and localEchoEnabled.
void Console::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
Console::mouseDoubleClickEvent.
Parameters
e
void Console::mousePressEvent (QMouseEvent * e) protected virtual
Console::mousePressEvent.
Parameters
e
void Console::putData (const QString & data)
Console::putData.
The function displays text in the console window, while converting escape sequences '\x1B' to colored HTML text.
Parameters
data of the type const QString. Incoming paint-text.
References ESC_END, ESC_START, and formatHtml().
Referenced by MainWindow::connectRTC().
void Console::setLocalEchoEnabled (bool set)
Console::setLocalEchoEnabled.
Parameters
set of the type bool.
References localEchoEnabled.
Member Data Documentation
QByteArray* Console::buffer private
Referenced by Console(), keyPressEvent(), and ~Console().
bool Console::localEchoEnabled private
Referenced by keyPressEvent(), and setLocalEchoEnabled().
The documentation for this class was generated from the following files:
console.h
console.cpp