SynchroTime: Interface Class Reference
Interface Class Reference abstract
Interface The base class Interface provides for the communication between Bootloader Client and Host Device.
#include <interface.h>
Signals
void infoMessage (const QVariant &message) const
void debugMessage (const QVariant &message) const
void errorMessage (const QVariant &message) const
Public Member Functions
Interface (QObject *parent=0)
Interface::Interface Constructor of the class Interface for creating objects with default values.
virtual qint64 writeTheData (const QByteArray &)=0
virtual bool readTheData (const quint32, const quint32 bytes=0U)=0
virtual QIODevice * getSocket (void)=0
virtual void initSocket (void)=0
virtual bool openSocket (void)=0
virtual void closeSocket (void)=0
void setBlockSize (const quint16 size)
Interface::setBlockSize.
quint16 getBlockSize (void) const
Interface::getBlockSize.
quint32 getReceivedBytes (void) const
Interface::getReceivedBytes.
void setTimer (QTimer *timer)
Interface::setTimer.
QTimer * getTimer (void)
Interface::getTimer.
void setTimeout (quint32 time)
Interface::setTimeout.
quint32 getTimeout (void) const
Interface::getTimeout.
QByteArray & getReceivedData (void)
Interface::getReceivedData.
Public Member Functions inherited from Base
Base (QObject *parent=0)
Base::Base.
virtual QString getClassName (void)
Base::getClassName.
QTextStream & stdOutput (void)
Base::stdOutput.
Private Attributes
QTimer * timer
Timer for Time-out method.
quint32 timeout
The timeout interval in milliseconds.
quint16 blockSize
Size of the data block for the communication protocol.
QByteArray receivedData
The received data.
Detailed Description
Interface The base class Interface provides for the communication between Bootloader Client and Host Device.
Base class interface provides two virtual methods for sending and receiving the instructions and the data. (Interface::writeTheData Interface::readTheData) These virtual methods are implemented in the other derived classes.
Constructor & Destructor Documentation
QT_USE_NAMESPACE Interface::Interface (QObject * parent = 0) explicit
Interface::Interface Constructor of the class Interface for creating objects with default values.
Create a instance of the class and call following init methods:
Interface::init()
Parameters
[in] parent Pointer to the parent object used for QObject
Member Function Documentation
virtual void Interface::closeSocket (void) pure virtual
Implemented in InterfaceSP.
Referenced by handleAdjustmentRequest(), handleCalibrationRequest(), handleInformationRequest(), handleResetRequest(), and handleSetRegisterRequest().
void Interface::debugMessage (const QVariant & message) const signal
void Interface::errorMessage (const QVariant & message) const signal
Referenced by InterfaceSP::handleTimeout().
quint16 Interface::getBlockSize (void) const
Interface::getBlockSize.
Gets the size of the data block of the communication protocol.
Returns
blockSize of the type quint16.
References blockSize.
Referenced by InterfaceSP::writeTheData().
quint32 Interface::getReceivedBytes (void) const
Interface::getReceivedBytes.
Gets the number of the received bytes.
Returns
receivedBytes of the type quint32.
References receivedData.
Referenced by InterfaceSP::readTheData().
QByteArray & Interface::getReceivedData (void)
Interface::getReceivedData.
Returns the received Data from the communication port.
Returns
receivedData of the type QByteArray&.
References receivedData.
Referenced by Tests::Case16(), Tests::Case17(), handleAdjustmentRequest(), handleCalibrationRequest(), handleInformationRequest(), InterfaceSP::handleReadyRead(), handleResetRequest(), handleSetRegisterRequest(), InterfaceSP::readTheData(), and InterfaceSP::writeTheData().
virtual QIODevice* Interface::getSocket (void) pure virtual
Implemented in InterfaceSP.
quint32 Interface::getTimeout (void) const
Interface::getTimeout.
Returns the Interval for a time-out in milliseconds.
Returns
timeout of the type quint32.
References timeout.
Referenced by InterfaceSP::handleReadyRead(), InterfaceSP::handleTimeout(), InterfaceSP::init(), and InterfaceSP::writeTheData().
QTimer * Interface::getTimer (void)
Interface::getTimer.
Returns the Pointer of object Timer.
Returns
*timer of the type QTimer.
References timer.
Referenced by InterfaceSP::handleReadyRead(), InterfaceSP::init(), and InterfaceSP::writeTheData().
void Interface::infoMessage (const QVariant & message) const signal
virtual void Interface::initSocket (void) pure virtual
Implemented in InterfaceSP.
virtual bool Interface::openSocket (void) pure virtual
Implemented in InterfaceSP.
Referenced by handleAdjustmentRequest(), handleCalibrationRequest(), handleInformationRequest(), handleResetRequest(), and handleSetRegisterRequest().
virtual bool Interface::readTheData (const quint32 , const quint32 bytes = 0U) pure virtual
Implemented in InterfaceSP.
Referenced by handleAdjustmentRequest(), handleCalibrationRequest(), handleInformationRequest(), handleResetRequest(), and handleSetRegisterRequest().
void Interface::setBlockSize (const quint16 size)
Interface::setBlockSize.
Sets the size of the data block for the communication protocol.
Parameters
size of typ const quint16
References blockSize.
void Interface::setTimeout (quint32 interval)
Interface::setTimeout.
Set the Interval for a time-out in milliseconds.
Parameters
interval of the type quint32.
References timeout.
Referenced by InterfaceSP::init().
void Interface::setTimer (QTimer * timer)
Interface::setTimer.
Set the Pointer of new object Timer.
Parameters
timer of the type QTimer*.
References timer.
Referenced by InterfaceSP::init().
virtual qint64 Interface::writeTheData (const QByteArray &) pure virtual
Implemented in InterfaceSP.
Referenced by handleAdjustmentRequest(), handleCalibrationRequest(), handleInformationRequest(), handleResetRequest(), and handleSetRegisterRequest().
Member Data Documentation
quint16 Interface::blockSize private
Size of the data block for the communication protocol.
Referenced by getBlockSize(), and setBlockSize().
QByteArray Interface::receivedData private
The received data.
Referenced by getReceivedBytes(), and getReceivedData().
quint32 Interface::timeout private
The timeout interval in milliseconds.
Referenced by getTimeout(), and setTimeout().
QTimer* Interface::timer private
Timer for Time-out method.
Referenced by getTimer(), and setTimer().
The documentation for this class was generated from the following files:
interface.h
interface.cpp