SynchroTime: RTC Class Reference
RTC Class Reference
The RTC class.
#include <rtc.h>
Public Slots
void informationRequestSlot ()
RTC::informationRequestSlot.
void adjustmentRequestSlot ()
RTC::adjustmentRequestSlot.
void calibrationRequestSlot ()
RTC::calibrationRequestSlot.
void resetRequestSlot ()
RTC::resetRequestSlot.
void setRegisterRequestSlot (const float newValue)
RTC::setRegisterRequestSlot.
void statusRequestSlot ()
RTC::versionRequestSlot.
Signals
void getRate (const float rate)
Signal function for determining the access rate via the serial interface.
void getData (const QString &data)
void portError (const QString &error)
Public Member Functions
RTC (const QString &portName, QObject *parent=0)
RTC::RTC Constructor for test purposes.
RTC (const Settings_t &portSettings, QObject *parent=0)
RTC::RTC Default Constructor.
~RTC ()
RTC::~RTC Default destructor.
bool isConnected () const
RTC::isConnected.
bool isBusy () const
RTC::isBusy.
Private Slots
void handleError (QSerialPort::SerialPortError error)
RTC::handleError.
Private Member Functions
bool openSerialPort () const
RTC::openSerialPort.
void connectToRTC ()
RTC::connectToRTC.
const QByteArray sendRequest (Request request, quint8 size=0, const quint8 *const data=nullptr)
RTC::sendRequest.
void informationRequest ()
RTC::informationRequest.
void adjustmentRequest ()
RTC::adjustmentRequest.
void calibrationRequest ()
RTC::calibrationRequest.
void resetRequest ()
RTC::resetRequest.
void setRegisterRequest (const float newValue)
RTC::setRegisterRequest.
bool statusRequest ()
RTC::statusRequest.
Private Attributes
QSerialPort * m_pSerialPort
bool m_isConnected
bool m_isBusy
QTimer * m_pTimerCheckConnection
float m_correctionFactor
Detailed Description
The RTC class.
The class is responsible for communication with the RTC device.
Constructor & Destructor Documentation
RTC::RTC (const QString & portName, QObject * parent = 0) explicit
RTC::RTC Constructor for test purposes.
Parameters
portName of the type const QString. Name of the port in the system.
parent of the type *QObject - pThread.
Note
There is no need to specify the parent. The parent will be a thread when we move our RTC object into it.
References connectToRTC(), handleError(), m_pSerialPort, m_pTimerCheckConnection, and statusRequestSlot().
RTC::RTC (const Settings_t & portSettings, QObject * parent = 0) explicit
RTC::RTC Default Constructor.
Parameters
portSettings of the type const Settings_t&. Reference to an parameters of the serial port.
parent of the type *QObject - pThread.
Note
There is no need to specify the parent. The parent will be a thread when we move our RTC object into it.
References Settings::baudRate, Settings::dataBits, Settings::flowControl, handleError(), m_isConnected, m_pSerialPort, m_pTimerCheckConnection, Settings::name, openSerialPort(), Settings::parity, Settings::requestRate, Settings::statusControlEnabled, statusRequestSlot(), and Settings::stopBits.
RTC::~RTC ()
RTC::~RTC Default destructor.
References m_pSerialPort, and m_pTimerCheckConnection.
Member Function Documentation
void RTC::adjustmentRequest () private
RTC::adjustmentRequest.
References ADJUST, ESC_RED, ESC_RESET, ESC_WHITE, ESC_YELLOW, getData(), sendRequest(), and STARTBYTE.
Referenced by adjustmentRequestSlot().
void RTC::adjustmentRequestSlot () slot
RTC::adjustmentRequestSlot.
References adjustmentRequest(), m_isBusy, and m_isConnected.
Referenced by MainWindow::connectRTC().
void RTC::calibrationRequest () private
RTC::calibrationRequest.
References CALIBR, ESC_RED, ESC_RESET, ESC_WHITE, ESC_YELLOW, getData(), sendRequest(), and STARTBYTE.
Referenced by calibrationRequestSlot().
void RTC::calibrationRequestSlot () slot
RTC::calibrationRequestSlot.
References calibrationRequest(), m_isBusy, and m_isConnected.
Referenced by MainWindow::connectRTC().
void RTC::connectToRTC () private
RTC::connectToRTC.
References m_isConnected, m_pSerialPort, statusRequest(), and WAIT_REBOOT.
Referenced by RTC().
void RTC::getData (const QString & data) signal
Referenced by adjustmentRequest(), calibrationRequest(), MainWindow::connectRTC(), informationRequest(), resetRequest(), setRegisterRequest(), and statusRequest().
void RTC::getRate (const float rate) signal
Signal function for determining the access rate via the serial interface.
Referenced by MainWindow::connectRTC(), and statusRequest().
void RTC::handleError (QSerialPort::SerialPortError error) private slot
RTC::handleError.
Parameters
error of the type enum QSerialPort::SerialPortError.
References m_pSerialPort, and portError().
Referenced by RTC().
void RTC::informationRequest () private
RTC::informationRequest.
References ESC_RED, ESC_RESET, ESC_WHITE, getData(), INFO, m_correctionFactor, sendRequest(), and STARTBYTE.
Referenced by informationRequestSlot().
void RTC::informationRequestSlot () slot
RTC::informationRequestSlot.
References informationRequest(), m_isBusy, and m_isConnected.
Referenced by MainWindow::connectRTC().
bool RTC::isBusy () const
RTC::isBusy.
Returns
True if the Serial Port is busy, otherwise false.
References m_isBusy.
bool RTC::isConnected () const
RTC::isConnected.
Returns
True if the RTC device is connected, otherwise false.
References m_isConnected.
Referenced by MainWindow::connectRTC().
bool RTC::openSerialPort () const private
RTC::openSerialPort.
Returns
True if the serial port is open, otherwise false.
References m_pSerialPort, and WAIT_REBOOT.
Referenced by RTC().
void RTC::portError (const QString & error) signal
Referenced by MainWindow::connectRTC(), handleError(), sendRequest(), and statusRequest().
void RTC::resetRequest () private
RTC::resetRequest.
References ESC_RED, ESC_RESET, ESC_WHITE, ESC_YELLOW, getData(), RESET, sendRequest(), and STARTBYTE.
Referenced by resetRequestSlot().
void RTC::resetRequestSlot () slot
RTC::resetRequestSlot.
References m_isBusy, m_isConnected, and resetRequest().
Referenced by MainWindow::connectRTC().
const QByteArray RTC::sendRequest (Request request, quint8 size = 0, const quint8 *const data = nullptr) private
RTC::sendRequest.
Parameters
request of the type enum Request.
size of the type quint8.
data Sent data of type byte array.
Returns
Data array of the type const QByteArray.
References m_isBusy, m_pSerialPort, portError(), STARTBYTE, and WAIT_TIME.
Referenced by adjustmentRequest(), calibrationRequest(), informationRequest(), resetRequest(), setRegisterRequest(), and statusRequest().
void RTC::setRegisterRequest (const float newValue) private
RTC::setRegisterRequest.
Parameters
newValue of the type const float. The new Value for Offset Register.
References ESC_RED, ESC_RESET, ESC_WHITE, ESC_YELLOW, getData(), sendRequest(), SETREG, and STARTBYTE.
Referenced by setRegisterRequestSlot().
void RTC::setRegisterRequestSlot (const float newValue) slot
RTC::setRegisterRequestSlot.
Parameters
newValue of the type const float.
References m_isBusy, m_isConnected, and setRegisterRequest().
Referenced by MainWindow::connectRTC().
bool RTC::statusRequest () private
RTC::statusRequest.
Returns
True if the RTC status was successful, otherwise false.
References ESC_RED, ESC_RESET, getData(), getRate(), m_pSerialPort, portError(), sendRequest(), STARTBYTE, STATUS, STATUS_DISCONNECTION, STATUS_ERROR, STATUS_INPUT_DATA_TOLONG, STATUS_INVALID_PARAMETER, STATUS_NOT_SUPPORTED, STATUS_SUCCESS, and STATUS_UNKNOWN_ERROR.
Referenced by connectToRTC(), and statusRequestSlot().
void RTC::statusRequestSlot () slot
RTC::versionRequestSlot.
References m_isBusy, m_isConnected, and statusRequest().
Referenced by RTC().
Member Data Documentation
float RTC::m_correctionFactor private
Referenced by informationRequest().
bool RTC::m_isBusy private
Referenced by adjustmentRequestSlot(), calibrationRequestSlot(), informationRequestSlot(), isBusy(), resetRequestSlot(), sendRequest(), setRegisterRequestSlot(), and statusRequestSlot().
bool RTC::m_isConnected private
Referenced by adjustmentRequestSlot(), calibrationRequestSlot(), connectToRTC(), informationRequestSlot(), isConnected(), resetRequestSlot(), RTC(), setRegisterRequestSlot(), and statusRequestSlot().
QSerialPort* RTC::m_pSerialPort private
Referenced by connectToRTC(), handleError(), openSerialPort(), RTC(), sendRequest(), statusRequest(), and ~RTC().
QTimer* RTC::m_pTimerCheckConnection private
Referenced by RTC(), and ~RTC().
The documentation for this class was generated from the following files:
rtc.h
rtc.cpp