SynchroTime: Session Class Reference
Session Class Reference
#include <session.h>
Public Member Functions
Session (QObject *parent=0)
Session (QObject *parent, Interface *const interface)
Interface * getInterface (void)
void setInterface (Interface *const interface)
Private Attributes
Interface * interface
Constructor & Destructor Documentation
Session::Session (QObject * parent = 0)
Session::Session (QObject * parent, Interface *const interface)
Member Function Documentation
Interface * Session::getInterface (void)
References interface.
Referenced by handleAdjustmentRequest(), handleCalibrationRequest(), handleInformationRequest(), handleResetRequest(), and handleSetRegisterRequest().
void Session::setInterface (Interface *const interface)
Member Data Documentation
Interface* Session::interface private
Referenced by getInterface().
The documentation for this class was generated from the following files:
session.h
session.cpp