SynchroTime: Tests Class Reference
Tests Class Reference
The Tests class The class includes all test cases.
Public Slots
void handleResults (const int value)
Tests::handleResults Implementation of a slot to fix the available serial ports.
Public Member Functions
Tests ()
Tests::Tests Constructor for class Tests.
Private Slots
void initTestCase ()
void cleanupTestCase ()
void Case1_data ()
Tests::Case1_data Data for Test Case 1.
void Case1 ()
Tests::Case1 Dummy Test Case.
void Case14 ()
Tests::Case14 Info about all available in system serial ports. When using a separate thread.
void Case15 ()
Tests::Case15 Prepare a new object Serial Port.
void Case16 ()
Tests::Case16 Checking communication with the device via the serial interface.
void Case17 ()
Tests::Case17 Checking communication with the device via the serial interface.
Private Attributes
int numberOfPorts
Detailed Description
The Tests class The class includes all test cases.
Constructor & Destructor Documentation
Tests::Tests ()
Tests::Tests Constructor for class Tests.
Member Function Documentation
void Tests::Case1 () private slot
Tests::Case1 Dummy Test Case.
void Tests::Case14 () private slot
Tests::Case14 Info about all available in system serial ports. When using a separate thread.
References handleResults(), and SerialThread::resultReady().
void Tests::Case15 () private slot
Tests::Case15 Prepare a new object Serial Port.
References InterfaceSP::getSerialPort().
void Tests::Case16 () private slot
Tests::Case16 Checking communication with the device via the serial interface.
Note
For correct testing, sketch firmware is required ../arduino/synchro_RTC_old.ino
References InterfaceSP::getPortName(), Interface::getReceivedData(), InterfaceSP::getSerialPort(), InterfaceSP::readTheData(), InterfaceSP::searchSerialPort(), and InterfaceSP::writeTheData().
void Tests::Case17 () private slot
Tests::Case17 Checking communication with the device via the serial interface.
Note
For correct testing, sketch firmware is required ../arduino/synchro_RTC_old.ino
References InterfaceSP::getPortName(), Interface::getReceivedData(), InterfaceSP::getSerialPort(), InterfaceSP::readTheData(), and InterfaceSP::writeTheData().
void Tests::Case1_data () private slot
Tests::Case1_data Data for Test Case 1.
void Tests::cleanupTestCase () private slot
void Tests::handleResults (const int value) slot
Tests::handleResults Implementation of a slot to fix the available serial ports.
Parameters
value of type const int
References numberOfPorts.
Referenced by Case14().
void Tests::initTestCase () private slot
Member Data Documentation
int Tests::numberOfPorts private
Referenced by handleResults().
The documentation for this class was generated from the following file:
tests.cpp