SynchroTime: SettingsDialog Class Reference
SettingsDialog Class Reference
The SettingsDialog class.
#include <settingsdialog.h>
Public Slots
void show ()
SettingsDialog::show.
Public Member Functions
SettingsDialog (QWidget *parent=0)
SettingsDialog::SettingsDialog.
~SettingsDialog ()
SettingsDialog::~SettingsDialog.
Settings settings () const
SettingsDialog::settings.
Settings * serialPortSettings ()
void fillSettingsUi ()
SettingsDialog::fillSettingsUi.
Private Slots
void showPortInfo (int idx)
SettingsDialog::showPortInfo.
void apply ()
SettingsDialog::apply.
void cansel ()
SettingsDialog::cansel.
void reset ()
SettingsDialog::reset.
void checkCustomBaudRatePolicy (int idx)
SettingsDialog::checkCustomBaudRatePolicy.
void checkCustomDevicePathPolicy (int idx)
SettingsDialog::checkCustomDevicePathPolicy.
Private Member Functions
void fillPortsParameters ()
SettingsDialog::fillPortsParameters.
void fillPortsInfo ()
SettingsDialog::fillPortsInfo.
void updateSettings ()
SettingsDialog::updateSettings.
Private Attributes
Ui::SettingsDialog * ui
Settings currentSettings
QIntValidator * intValidator
Detailed Description
The SettingsDialog class.
Constructor & Destructor Documentation
SettingsDialog::SettingsDialog (QWidget * parent = 0) explicit
SettingsDialog::SettingsDialog.
Parameters
parent
References apply(), cansel(), checkCustomBaudRatePolicy(), checkCustomDevicePathPolicy(), fillPortsInfo(), fillPortsParameters(), intValidator, reset(), showPortInfo(), ui, and updateSettings().
SettingsDialog::~SettingsDialog ()
SettingsDialog::~SettingsDialog.
References ui.
Member Function Documentation
void SettingsDialog::apply () private slot
SettingsDialog::apply.
References currentSettings, Settings::isChanged, and updateSettings().
Referenced by SettingsDialog().
void SettingsDialog::cansel () private slot
SettingsDialog::cansel.
References fillSettingsUi().
Referenced by SettingsDialog().
void SettingsDialog::checkCustomBaudRatePolicy (int idx) private slot
SettingsDialog::checkCustomBaudRatePolicy.
Parameters
idx
References intValidator, and ui.
Referenced by SettingsDialog().
void SettingsDialog::checkCustomDevicePathPolicy (int idx) private slot
SettingsDialog::checkCustomDevicePathPolicy.
Parameters
idx
References ui.
Referenced by SettingsDialog().
void SettingsDialog::fillPortsInfo () private
SettingsDialog::fillPortsInfo.
References blankString, and ui.
Referenced by SettingsDialog(), and show().
void SettingsDialog::fillPortsParameters () private
SettingsDialog::fillPortsParameters.
References ui.
Referenced by SettingsDialog().
void SettingsDialog::fillSettingsUi ()
SettingsDialog::fillSettingsUi.
References Settings::baudRate, currentSettings, Settings::name, Settings::stringBaudRate, Settings::stringDataBits, Settings::stringFlowControl, Settings::stringParity, Settings::stringStopBits, and ui.
Referenced by cansel(), and MainWindow::MainWindow().
void SettingsDialog::reset () private slot
SettingsDialog::reset.
References ui.
Referenced by SettingsDialog().
Settings_t * SettingsDialog::serialPortSettings ()
References currentSettings.
Referenced by MainWindow::readSettings().
Settings_t SettingsDialog::settings () const
SettingsDialog::settings.
Returns
References currentSettings.
Referenced by MainWindow::connectRTC(), and MainWindow::writeSettings().
void SettingsDialog::show () slot
SettingsDialog::show.
References fillPortsInfo().
Referenced by MainWindow::MainWindow().
void SettingsDialog::showPortInfo (int idx) private slot
SettingsDialog::showPortInfo.
Parameters
idx
References blankString, and ui.
Referenced by SettingsDialog().
void SettingsDialog::updateSettings () private
SettingsDialog::updateSettings.
References Settings::baudRate, currentSettings, Settings::dataBits, Settings::flowControl, Settings::localEchoEnabled, Settings::name, Settings::parity, Settings::stopBits, Settings::stringBaudRate, Settings::stringDataBits, Settings::stringFlowControl, Settings::stringParity, Settings::stringStopBits, and ui.
Referenced by apply(), and SettingsDialog().
Member Data Documentation
Settings SettingsDialog::currentSettings private
Referenced by apply(), fillSettingsUi(), serialPortSettings(), settings(), and updateSettings().
QIntValidator* SettingsDialog::intValidator private
Referenced by checkCustomBaudRatePolicy(), and SettingsDialog().
Ui::SettingsDialog* SettingsDialog::ui private
Referenced by checkCustomBaudRatePolicy(), checkCustomDevicePathPolicy(), fillPortsInfo(), fillPortsParameters(), fillSettingsUi(), reset(), SettingsDialog(), showPortInfo(), updateSettings(), and ~SettingsDialog().
The documentation for this class was generated from the following files:
settingsdialog.h
settingsdialog.cpp