SynchroTime: Base Class Reference
Base Class Reference
#include <base.h>
Public Member Functions
Base (QObject *parent=0)
Base::Base.
virtual QString getClassName (void)
Base::getClassName.
QTextStream & stdOutput (void)
Base::stdOutput.
Private Attributes
QTextStream standardOutput
Output stream for all messages.
Constructor & Destructor Documentation
Base::Base (QObject * parent = 0) explicit
Base::Base.
The Constructor for class Basse
Member Function Documentation
QString Base::getClassName (void) virtual
Base::getClassName.
Get class name as string
Returns
className of the type QString.
QTextStream & Base::stdOutput (void)
Base::stdOutput.
Output stream for all messages.
Returns
standardOutput of the type QTextStream&.
References standardOutput.
Referenced by InterfaceSP::handleError(), InterfaceSP::handleTimeout(), InterfaceSP::readTheData(), InterfaceSP::searchAllSerialPort(), and InterfaceSP::writeTheData().
Member Data Documentation
QTextStream Base::standardOutput private
Output stream for all messages.
Referenced by stdOutput().
The documentation for this class was generated from the following files:
base.h
base.cpp