SynchroTime: MainWindow Class Reference
MainWindow Class Reference
The MainWindow class.
#include <mainwindow.h>
Signals
void setRegister (const float value)
Public Member Functions
MainWindow (QWidget *parent=0)
MainWindow::MainWindow Constructor of the main application window.
~MainWindow ()
MainWindow::~MainWindow Destructor in which the completion of a separate thread is checked.
Protected Member Functions
void closeEvent (QCloseEvent *event) Q_DECL_OVERRIDE
MainWindow::closeEvent Handle program completion event.
Private Slots
void connectRTC ()
MainWindow::connectRTC Procedure for creating a separate thread for communication with a device.
void disconnectRTC ()
MainWindow::disconnectRTC The procedure performs a correct disconnection from the device.
void selectConsoleFont ()
MainWindow::selectConsoleFont Slot for the font selection dialog.
void setRegisterSlot ()
MainWindow::setRegisterSlot Slot for writing to the shift register.
void tickClock ()
MainWindow::tickClock Slot for displaying the time of day.
void help ()
MainWindow::help slot Brief description of how to use the application.
void aboutQt ()
MainWindow::aboutQt A slot for issuing information about the Qt-Framework used.
void about ()
MainWindow::about About the app.
void putRate (const float rate)
MainWindow::putRate Displays the time of access to the device through the serial port.
void handleError (const QString &error)
MainWindow::handleError Slot for handling errors when communicating with a remote device.
Private Member Functions
void readSettings (void)
MainWindow::readSettings The function reads the parameters necessary for the user interface that were saved in the previous session.
void writeSettings (void) const
MainWindow::writeSettings The function saves the user interface parameters that have been changed by the user in the current session.
void actionsTrigger (bool value) const
MainWindow::actionsTrigger.
void showStatusMessage (const QString &message) const
MainWindow::showStatusMessage.
Private Attributes
Ui::MainWindow * ui
QLabel * rate
QLabel * status
QLCDNumber * clock
QTimer * m_pTimer
Console * m_pConsole
SettingsDialog * m_pSettingsDialog
QThread * m_pThread
RTC * m_pRTC
Detailed Description
The MainWindow class.
The MainWindow class provides the user with interface methods for the main application window.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0) explicit
MainWindow::MainWindow Constructor of the main application window.
Parameters
parent of the type QWidget
References about(), aboutQt(), actionsTrigger(), clock, connectRTC(), disconnectRTC(), SettingsDialog::fillSettingsUi(), help(), m_pConsole, m_pSettingsDialog, m_pTimer, rate, readSettings(), selectConsoleFont(), setRegisterSlot(), SettingsDialog::show(), status, tickClock(), and ui.
MainWindow::~MainWindow ()
MainWindow::~MainWindow Destructor in which the completion of a separate thread is checked.
References m_pThread, ui, and WAIT_FOR_STREAM.
Member Function Documentation
void MainWindow::about () private slot
MainWindow::about About the app.
Referenced by MainWindow().
void MainWindow::aboutQt () private slot
MainWindow::aboutQt A slot for issuing information about the Qt-Framework used.
Referenced by MainWindow().
void MainWindow::actionsTrigger (bool value) const private
MainWindow::actionsTrigger.
Parameters
value of the type bool: true if connected, false if disconnected.
References ui.
Referenced by connectRTC(), disconnectRTC(), and MainWindow().
void MainWindow::closeEvent (QCloseEvent * event) protected
MainWindow::closeEvent Handle program completion event.
Before exiting the program, the user interface parameters are automatically saved.
Parameters
event of type QCloseEvent*
References writeSettings().
void MainWindow::connectRTC () private slot
MainWindow::connectRTC Procedure for creating a separate thread for communication with a device.
References actionsTrigger(), RTC::adjustmentRequestSlot(), RTC::calibrationRequestSlot(), RTC::getData(), RTC::getRate(), handleError(), RTC::informationRequestSlot(), RTC::isConnected(), m_pConsole, m_pRTC, m_pSettingsDialog, m_pThread, RTC::portError(), Console::putData(), putRate(), RTC::resetRequestSlot(), setRegister(), RTC::setRegisterRequestSlot(), SettingsDialog::settings(), showStatusMessage(), ui, and WAIT_FOR_STREAM.
Referenced by MainWindow().
void MainWindow::disconnectRTC () private slot
MainWindow::disconnectRTC The procedure performs a correct disconnection from the device.
References actionsTrigger(), m_pConsole, m_pThread, rate, showStatusMessage(), and WAIT_FOR_STREAM.
Referenced by handleError(), and MainWindow().
void MainWindow::handleError (const QString & error) private slot
MainWindow::handleError Slot for handling errors when communicating with a remote device.
Parameters
error of the type QString
References disconnectRTC().
Referenced by connectRTC().
void MainWindow::help () private slot
MainWindow::help slot Brief description of how to use the application.
Referenced by MainWindow().
void MainWindow::putRate (const float rate) private slot
MainWindow::putRate Displays the time of access to the device through the serial port.
Parameters
rate of the type const float
References Settings::accessRateEnabled, m_pSettingsDialog, and SettingsDialog::settings().
Referenced by connectRTC().
void MainWindow::readSettings (void) private
MainWindow::readSettings The function reads the parameters necessary for the user interface that were saved in the previous session.
The following important parameters will be read as:
the position of the window on the screen and window size,
interface font and its size,
the user interface settings (overwrite of the data, recurse of dir's, etc.),
the serial port options,
and other additional parameters.
References Settings::accessRateEnabled, Settings::baudRate, Settings::correctionFactor, m_pConsole, m_pSettingsDialog, Settings::name, Settings::requestRate, SettingsDialog::serialPortSettings(), SETTINGS_FILE, Settings::statusControlEnabled, Settings::stringBaudRate, Settings::stringDataBits, Settings::stringFlowControl, Settings::stringParity, and Settings::stringStopBits.
Referenced by MainWindow().
void MainWindow::selectConsoleFont (void) private slot
MainWindow::selectConsoleFont Slot for the font selection dialog.
Selection of the console font. The default font is Monospace, 10 points.
Note
The font is installed only for the console window, i.s. not for all graphic forms!
References m_pConsole.
Referenced by MainWindow().
void MainWindow::setRegister (const float value) signal
Referenced by connectRTC(), and setRegisterSlot().
void MainWindow::setRegisterSlot () private slot
MainWindow::setRegisterSlot Slot for writing to the shift register.
References m_pRTC, and setRegister().
Referenced by MainWindow().
void MainWindow::showStatusMessage (const QString & message) const private
MainWindow::showStatusMessage.
Parameters
message
References status.
Referenced by connectRTC(), and disconnectRTC().
void MainWindow::tickClock () private slot
MainWindow::tickClock Slot for displaying the time of day.
References clock.
Referenced by MainWindow().
void MainWindow::writeSettings (void) const private
MainWindow::writeSettings The function saves the user interface parameters that have been changed by the user in the current session.
The following important parameters will be updated as:
the position of the window on the screen and window size,
interface font and its size,
the user interface settings (overwrite of the data, recurse of dir's, etc.),
the serial port options,
and other additional parameters.
References Settings::accessRateEnabled, Settings::baudRate, Settings::correctionFactor, Settings::isChanged, m_pConsole, m_pSettingsDialog, Settings::name, Settings::requestRate, SettingsDialog::settings(), SETTINGS_FILE, Settings::statusControlEnabled, Settings::stringDataBits, Settings::stringFlowControl, Settings::stringParity, and Settings::stringStopBits.
Referenced by closeEvent().
Member Data Documentation
QLCDNumber* MainWindow::clock private
Referenced by MainWindow(), and tickClock().
Console* MainWindow::m_pConsole private
Referenced by connectRTC(), disconnectRTC(), MainWindow(), readSettings(), selectConsoleFont(), and writeSettings().
RTC* MainWindow::m_pRTC private
Referenced by connectRTC(), and setRegisterSlot().
SettingsDialog* MainWindow::m_pSettingsDialog private
Referenced by connectRTC(), MainWindow(), putRate(), readSettings(), and writeSettings().
QThread* MainWindow::m_pThread private
Referenced by connectRTC(), disconnectRTC(), and ~MainWindow().
QTimer* MainWindow::m_pTimer private
Referenced by MainWindow().
QLabel* MainWindow::rate private
Referenced by disconnectRTC(), and MainWindow().
QLabel* MainWindow::status private
Referenced by MainWindow(), and showStatusMessage().
Ui::MainWindow* MainWindow::ui private
Referenced by actionsTrigger(), connectRTC(), MainWindow(), and ~MainWindow().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp